SELECT SYSDATE, LEVEL 
FROM dual
CONNECT BY LEVEL <=10;

SELECT SYSDATE+LEVEL dt
FROM dual
CONNECT BY LEVEL <=10;

--해당월의 1일
SELECT TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')
FROM dual;

--해당월의 일자
SELECT TO_CHAR(LAST_DAY(SYSDATE),'DD')
FROM dual;


-- 해당 주차 구하기
SELECT TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1 dt, 
       TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D')
FROM dual
CONNECT BY LEVEL <=TO_CHAR(LAST_DAY(SYSDATE),'DD');



SELECT TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1 dt, 
       TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'IW')iw,
       TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'DAY')day
FROM dual
CONNECT BY LEVEL <=TO_CHAR(LAST_DAY(SYSDATE),'DD');




SELECT TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1 dt, 
       TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'IW')iw,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),1,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)SUN,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),2,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)MON,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),3,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)TUE,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),4,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)WED,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),5,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)THU,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),6,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)FRI,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),7,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)SAT
FROM dual
CONNECT BY LEVEL <=TO_CHAR(LAST_DAY(SYSDATE),'DD');



SELECT DECODE(dt, 1, iw + 1, iw) D, MIN(SUN),MIN(MON),MIN(TUE),MIN(WED),MIN(THU),MIN(FRI),MIN(SAT)
FROM
(SELECT TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1 dt, 
       TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'IW')iw,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),1,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)SUN,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),2,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)MON,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),3,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)TUE,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),4,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)WED,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),5,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)THU,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),6,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)FRI,
       DECODE(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1,'D'),7,TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01','YYYYMMDD')+LEVEL-1)SAT
FROM dual
CONNECT BY LEVEL <=TO_CHAR(LAST_DAY(SYSDATE),'DD'))
GROUP BY DECODE(dt, 1, iw + 1, iw)
ORDER BY DECODE(dt, 1, iw + 1, iw);









